services:
  jenkins:
    build: .
    image: fos-jenkins-blueocean:lts
    container_name: jenkins-master
    restart: on-failure
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro

volumes:
  jenkins_home:
  jenkins_docker_certs:
